Automatically create cache_dir from cache_file_name
You get a pretty unhelpful error message when specifying a cache_file_name in a directory that doesn't exist, e.g. cache_file_name="./cache/data.map"

FileNotFoundError: [Errno 2] No such file or directory: '/.../cache/tmp48r61siw'