Fix "'BertTokenizerFast' object has no attribute 'max_len'" (#1640)
Tensorflow 2.3.0 gives:
 FutureWarning: The `max_len` attribute has been deprecated and will be removed in a future version, use `model_max_length` instead.

Tensorflow 2.4.0 gives:
AttributeError 'BertTokenizerFast' object has no attribute 'max_len'

Co-authored-by: Marcin Flis <marcinf@qualtrics.com>